spring.application.name=dulcerojo
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/dulcerojodb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:cambiame_local}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Perfil local
spring.profiles.include=local

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false